substitutions:
  standing_desk_uart_rx_pin: D2
  standing_desk_up_pin: D7
  standing_desk_down_pin: D8
  standing_desk_variant: "flexispot_e7"
  standing_desk_min_height: "23.6"
  standing_desk_max_height: "49.2"

  # Presets
  button_bit1_pin: D7
  button_bit2_pin: D8
  button_bit4_pin: D6
  button_m_pin: D1